### ISSUE TITLE
Unresolved identifier Process

### ISSUE THREAD

**Issue by RajChanchal** [billwang1990/SwiftDenyPtrace#1]
Hi,
I wanted to use this code into my Swift 3 project, But it gives me an error saying unresolved identifier 'Process' in main.swift class

**Comment by RajChanchal** [comment]
I found that Swift 3 alternative for `Process `is `CommandLine`
But following line in main.swift class has error:
`UIApplicationMain(CommandLine.argc, CommandLine.unsafeArgv, nil, NSStringFromClass(AppDelegate))`

`<my_app_directory_path>/main.swift:14:53: Cannot convert value of type 'UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>' (aka 'UnsafeMutablePointer<Optional<UnsafeMutablePointer<Int8>>>') to expected argument type 'UnsafeMutablePointer<UnsafeMutablePointer<Int8>>!'`

**Comment by billwang1990** [comment]
Thanks a lot. I wrote these code long time ago. You are right, we should update it for Swift 3. I will take a look at your pr.

**Comment by RajChanchal** [comment]
DenyPtrace.c file has one string 'ptrace', this needs to be obfuscated. I have updated its code to obfuscate it.

**Comment by billwang1990** [comment]
Thanks, you can create a pr. 👍 👍 👍

**Comment by RajChanchal** [comment]
@billwang1990 How to use this ptrace? If I use it, I cannot even run even the adhoc archived build too.

**Comment by billwang1990** [comment]
@RajChanchal Hi, I already updated the README.md. :)

**Comment by RajChanchal** [comment]
Were you able to run application after you implemented it? I couldn't, not even in adhoc build!!

**Comment by billwang1990** [comment]
Yes, I did. I archived my app and extract the adhoc ipa, then installed it on my device. I'm not pretty sure what you mean. Can you compile it and export the ipa file. Or it will crash when you run it? And one thing you should notice is that in my code, I disable the ptrace no matter debug or release mode. Which means you can not use xcode to debug it. You can add a marco to fix it.

**Comment by RajChanchal** [comment]
I did the same, installed the adhoc build and it just crashed at start. Did yours work fine? And yes, you are right, I cannot use in xcode debug since you disabled ptrace.

**Comment by RajChanchal** [comment]
@billwang1990 I think it is not issue with your code. It's with mine when I was confiscating string 'ptrace' You can close this issue, as you have already written a good ReadMe about your Swift updates.
